networks:
  app_ecommerce:


services:

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_USER: appuser
      MYSQL_PASSWORD: abc123
    networks:
      - app_ecommerce
    ports:
      - 3306:3306

  ecommerce:
    build: .
    networks:
      - app_ecommerce
    environment:
      DATABASE_HOST: database
      DATABASE_USER: root
      DATABASE_PASS: abc123
      DATABASE_NAME: ecommerce
    depends_on:
      - database
    restart: on-failure
    volumes:
      - .:/srv/app
    command: sh -c "npm install && npm run start:dev"
    
   